/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 ./brain.gltf 
Author of 3D Model: 3DRT STUDIOS (https://sketchfab.com/Hanako.com)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/human-brain-7a27c17fd6c0488bb31ab093236a47fb
Title: Human Brain
*/

import React, { useRef} from 'react'
import {useFrame } from '@react-three/fiber';
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/brain.gltf')


  const brainRef = useRef();
  useFrame(() => {
    if (brainRef.current) {
      // brainRef.current.rotation.y += 0.001; // Rotate the brain around the y-axis
    }
  });


  return (
    
    <group ref={brainRef} {...props} dispose={null}>
      <mesh geometry={nodes.Object_5.geometry} material={materials.material_0} scale={0.02} />
    </group>
  )
}

useGLTF.preload('/brain.gltf')
