/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 public/food_kiwi_01_4k.gltf -r public 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/food_kiwi_01_4k.gltf')
  return (
    <group {...props} dispose={null} scale={30}>
      <mesh geometry={nodes.food_kiwi_01.geometry} material={materials.food_kiwi_01} />
    </group>
  )
}

useGLTF.preload('/food_kiwi_01_4k.gltf')
